name: func_and_collections
description: Modulo da academia do flutter de funcoes e colecoes.
version: 1.0.0
# homepage: https://www.academiadoflutter.com.br

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
